
server:
  port: 8002

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://node1:7001/eureka/,http://node2:7002/eureka/,http://node3:7003/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: user-provider-server
  datasource:
    url: jdbc:mysql://47.93.99.166:3306/user?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
